name 'maestrodev-test'
version '1.0.0'

license 'Apache License, Version 2.0'
project_page 'http://github.com/maestrodev/puppet-blacksmith'
source 'http://github.com/maestrodev/puppet-blacksmith'
summary 'Testing Puppet module operations'
description 'Testing Puppet module operations'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
